"""Estrutura inicial do SGE

Revision ID: 037750e0ef9b
Revises: 
Create Date: 2026-07-31 19:42:05.461393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037750e0ef9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anos_letivos',
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('situacao', sa.Enum('planejamento', 'em_andamento', 'encerrado', name='situacao_ano_letivo', native_enum=False), nullable=False),
    sa.Column('corrente', sa.Boolean(), nullable=False),
    sa.Column('media_aprovacao', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('media_recuperacao', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('frequencia_minima', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota_maxima', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ano >= 2000 AND ano <= 2100', name=op.f('ck_anos_letivos_ano_plausivel')),
    sa.CheckConstraint('data_fim > data_inicio', name=op.f('ck_anos_letivos_periodo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anos_letivos'))
    )
    with op.batch_alter_table('anos_letivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anos_letivos_ano'), ['ano'], unique=True)
        batch_op.create_index(batch_op.f('ix_anos_letivos_corrente'), ['corrente'], unique=False)
        batch_op.create_index(batch_op.f('ix_anos_letivos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_anos_letivos_situacao'), ['situacao'], unique=False)

    op.create_table('configuracoes_escola',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('codigo_inep', sa.String(length=20), nullable=True),
    sa.Column('diretor', sa.String(length=150), nullable=True),
    sa.Column('secretario', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('site', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.Column('media_aprovacao', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('media_recuperacao', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('frequencia_minima', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota_maxima', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('quantidade_periodos', sa.Integer(), nullable=False),
    sa.Column('backup_automatico', sa.Boolean(), nullable=False),
    sa.Column('backup_hora', sa.String(length=5), nullable=False),
    sa.Column('mensagem_login', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracoes_escola'))
    )
    with op.batch_alter_table('configuracoes_escola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_escola_criado_em'), ['criado_em'], unique=False)

    op.create_table('disciplinas',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplinas'))
    )
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disciplinas_ativa'), ['ativa'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplinas_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_disciplinas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplinas_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplinas_nome'), ['nome'], unique=False)
        batch_op.create_index('ix_disciplinas_nome_normalizado', ['nome_normalizado'], unique=False)

    op.create_table('salas',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('bloco', sa.String(length=40), nullable=True),
    sa.Column('andar', sa.String(length=20), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('possui_projetor', sa.Boolean(), nullable=False),
    sa.Column('possui_ar_condicionado', sa.Boolean(), nullable=False),
    sa.Column('acessivel', sa.Boolean(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salas'))
    )
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_salas_nome'), ['nome'], unique=True)

    op.create_table('series',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('nivel_ensino', sa.Enum('infantil', 'fundamental_i', 'fundamental_ii', 'medio', 'eja', name='nivel_ensino', native_enum=False), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('idade_recomendada', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('nome', 'nivel_ensino', name='serie_unica_por_nivel')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_nivel_ensino'), ['nivel_ensino'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_ordem'), ['ordem'], unique=False)

    op.create_table('tempos_aula',
    sa.Column('turno', sa.Enum('matutino', 'vespertino', 'noturno', 'integral', name='turno', native_enum=False), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('e_intervalo', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hora_fim > hora_inicio', name=op.f('ck_tempos_aula_intervalo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tempos_aula')),
    sa.UniqueConstraint('turno', 'ordem', name='tempo_unico_por_turno')
    )
    with op.batch_alter_table('tempos_aula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tempos_aula_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_tempos_aula_turno'), ['turno'], unique=False)

    op.create_table('usuarios',
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('senha_alterada_em', sa.DateTime(), nullable=True),
    sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('papel', sa.Enum('administrador', 'direcao', 'secretaria', 'professor', 'aluno', 'responsavel', name='papel_usuario', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login_ip', sa.String(length=45), nullable=True),
    sa.Column('tentativas_falhas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index('ix_usuarios_nome_normalizado', ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_papel'), ['papel'], unique=False)
        batch_op.create_index('ix_usuarios_papel_ativo', ['papel', 'ativo'], unique=False)

    op.create_table('alunos',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('naturalidade', sa.String(length=80), nullable=True),
    sa.Column('uf_naturalidade', sa.String(length=2), nullable=True),
    sa.Column('nacionalidade', sa.String(length=60), nullable=False),
    sa.Column('certidao_nascimento', sa.String(length=60), nullable=True),
    sa.Column('nis', sa.String(length=11), nullable=True),
    sa.Column('cartao_sus', sa.String(length=15), nullable=True),
    sa.Column('tipo_sanguineo', sa.String(length=3), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('medicamentos_continuos', sa.Text(), nullable=True),
    sa.Column('condicoes_saude', sa.Text(), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=False),
    sa.Column('descricao_deficiencia', sa.Text(), nullable=True),
    sa.Column('necessita_acompanhante', sa.Boolean(), nullable=False),
    sa.Column('bolsista', sa.Boolean(), nullable=False),
    sa.Column('percentual_bolsa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('usa_transporte_escolar', sa.Boolean(), nullable=False),
    sa.Column('autorizado_sair_sozinho', sa.Boolean(), nullable=False),
    sa.Column('autoriza_uso_imagem', sa.Boolean(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'nao_informado', name='sexo', native_enum=False), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('situacao', sa.Enum('ativo', 'inativo', 'transferido', 'formado', 'desligado', name='situacao_cadastro', native_enum=False), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_alunos_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alunos'))
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_celular'), ['celular'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_alunos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_situacao'), ['situacao'], unique=False)
        batch_op.create_index('ix_alunos_situacao_nome', ['situacao', 'nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('funcionarios',
    sa.Column('matricula_funcional', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'viuvo', 'uniao_estavel', 'nao_informado', name='estado_civil', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'nao_informado', name='sexo', native_enum=False), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('situacao', sa.Enum('ativo', 'inativo', 'transferido', 'formado', 'desligado', name='situacao_cadastro', native_enum=False), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_funcionarios_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funcionarios'))
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_cargo'), ['cargo'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_celular'), ['celular'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_funcionarios_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_matricula_funcional'), ['matricula_funcional'], unique=True)
        batch_op.create_index(batch_op.f('ix_funcionarios_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_setor'), ['setor'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_situacao'), ['situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('logs_auditoria',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=150), nullable=True),
    sa.Column('acao', sa.Enum('criacao', 'atualizacao', 'exclusao', 'login', 'logout', 'login_falhou', 'senha_alterada', 'senha_recuperada', 'acesso_negado', 'backup', 'restauracao', 'exportacao', name='acao_auditoria', native_enum=False), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('endereco_ip', sa.String(length=45), nullable=True),
    sa.Column('navegador', sa.String(length=255), nullable=True),
    sa.Column('rota', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_logs_auditoria_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs_auditoria'))
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index('ix_logs_acao_data', ['acao', 'criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index('ix_logs_entidade', ['entidade', 'entidade_id'], unique=False)
        batch_op.create_index('ix_logs_usuario_data', ['usuario_id', 'criado_em'], unique=False)

    op.create_table('periodos_letivos',
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('encerrado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('data_fim > data_inicio', name=op.f('ck_periodos_letivos_periodo_valido')),
    sa.CheckConstraint('ordem >= 1 AND ordem <= 8', name=op.f('ck_periodos_letivos_ordem_plausivel')),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], name=op.f('fk_periodos_letivos_ano_letivo_id_anos_letivos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodos_letivos')),
    sa.UniqueConstraint('ano_letivo_id', 'ordem', name='ordem_unica_no_ano')
    )
    with op.batch_alter_table('periodos_letivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodos_letivos_ano_letivo_id'), ['ano_letivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_periodos_letivos_criado_em'), ['criado_em'], unique=False)

    op.create_table('professores',
    sa.Column('registro_funcional', sa.String(length=20), nullable=False),
    sa.Column('formacao', sa.String(length=150), nullable=True),
    sa.Column('titulacao', sa.String(length=60), nullable=True),
    sa.Column('instituicao_formacao', sa.String(length=150), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'viuvo', 'uniao_estavel', 'nao_informado', name='estado_civil', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'nao_informado', name='sexo', native_enum=False), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('situacao', sa.Enum('ativo', 'inativo', 'transferido', 'formado', 'desligado', name='situacao_cadastro', native_enum=False), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_professores_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professores'))
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professores_celular'), ['celular'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_registro_funcional'), ['registro_funcional'], unique=True)
        batch_op.create_index(batch_op.f('ix_professores_situacao'), ['situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('registros_backup',
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('automatico', sa.Boolean(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('gerado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['gerado_por_id'], ['usuarios.id'], name=op.f('fk_registros_backup_gerado_por_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registros_backup'))
    )
    with op.batch_alter_table('registros_backup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_backup_criado_em'), ['criado_em'], unique=False)

    op.create_table('responsaveis',
    sa.Column('profissao', sa.String(length=80), nullable=True),
    sa.Column('local_trabalho', sa.String(length=150), nullable=True),
    sa.Column('telefone_trabalho', sa.String(length=11), nullable=True),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'viuvo', 'uniao_estavel', 'nao_informado', name='estado_civil', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'nao_informado', name='sexo', native_enum=False), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('situacao', sa.Enum('ativo', 'inativo', 'transferido', 'formado', 'desligado', name='situacao_cadastro', native_enum=False), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_responsaveis_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsaveis'))
    )
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsaveis_celular'), ['celular'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_responsaveis_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_situacao'), ['situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('alunos_responsaveis',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.Enum('mae', 'pai', 'avo', 'tio', 'irmao', 'tutor_legal', 'outro', name='parentesco', native_enum=False), nullable=False),
    sa.Column('responsavel_legal', sa.Boolean(), nullable=False),
    sa.Column('responsavel_financeiro', sa.Boolean(), nullable=False),
    sa.Column('autorizado_buscar', sa.Boolean(), nullable=False),
    sa.Column('ordem_contato', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ordem_contato >= 1 AND ordem_contato <= 10', name=op.f('ck_alunos_responsaveis_ordem_plausivel')),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_alunos_responsaveis_aluno_id_alunos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], name=op.f('fk_alunos_responsaveis_responsavel_id_responsaveis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alunos_responsaveis')),
    sa.UniqueConstraint('aluno_id', 'responsavel_id', name='vinculo_unico')
    )
    with op.batch_alter_table('alunos_responsaveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_responsaveis_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_responsaveis_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_responsaveis_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('turmas',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('professor_regente_id', sa.Integer(), nullable=True),
    sa.Column('turno', sa.Enum('matutino', 'vespertino', 'noturno', 'integral', name='turno', native_enum=False), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('capacidade > 0', name=op.f('ck_turmas_capacidade_positiva')),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], name=op.f('fk_turmas_ano_letivo_id_anos_letivos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professor_regente_id'], ['professores.id'], name=op.f('fk_turmas_professor_regente_id_professores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], name=op.f('fk_turmas_sala_id_salas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], name=op.f('fk_turmas_serie_id_series'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turmas')),
    sa.UniqueConstraint('ano_letivo_id', 'serie_id', 'nome', name='turma_unica_no_ano')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_ano_letivo_id'), ['ano_letivo_id'], unique=False)
        batch_op.create_index('ix_turmas_ano_turno', ['ano_letivo_id', 'turno'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_ativa'), ['ativa'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_professor_regente_id'), ['professor_regente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_sala_id'), ['sala_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_turno'), ['turno'], unique=False)

    op.create_table('avisos',
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('resumo', sa.String(length=255), nullable=True),
    sa.Column('publico', sa.Enum('todos', 'equipe', 'professores', 'alunos', 'responsaveis', 'turma', name='publico_aviso', native_enum=False), nullable=False),
    sa.Column('prioridade', sa.Enum('baixa', 'normal', 'alta', 'urgente', name='prioridade_aviso', native_enum=False), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('fixado', sa.Boolean(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('anexo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_avisos_autor_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_avisos_turma_id_turmas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avisos'))
    )
    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avisos_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_data_inicio'), ['data_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_prioridade'), ['prioridade'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_publicado'), ['publicado'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_publico'), ['publico'], unique=False)
        batch_op.create_index('ix_avisos_publico_publicado', ['publico', 'publicado'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_turma_id'), ['turma_id'], unique=False)
        batch_op.create_index('ix_avisos_vigencia', ['data_inicio', 'data_fim'], unique=False)

    op.create_table('matriculas',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('situacao', sa.Enum('ativa', 'trancada', 'transferida', 'cancelada', 'concluida', name='situacao_matricula', native_enum=False), nullable=False),
    sa.Column('resultado_final', sa.Enum('aprovado', 'aprovado_conselho', 'recuperacao', 'reprovado', 'reprovado_falta', 'cursando', name='resultado_final', native_enum=False), nullable=False),
    sa.Column('media_geral', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentual_frequencia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_faltas', sa.Integer(), nullable=True),
    sa.Column('escola_origem', sa.String(length=150), nullable=True),
    sa.Column('escola_destino', sa.String(length=150), nullable=True),
    sa.Column('motivo_saida', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_matriculas_aluno_id_alunos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], name=op.f('fk_matriculas_ano_letivo_id_anos_letivos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_matriculas_turma_id_turmas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas')),
    sa.UniqueConstraint('aluno_id', 'ano_letivo_id', 'turma_id', name='matricula_unica')
    )
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriculas_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_ano_letivo_id'), ['ano_letivo_id'], unique=False)
        batch_op.create_index('ix_matriculas_ano_situacao', ['ano_letivo_id', 'situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_excluido_em'), ['excluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_matriculas_resultado_final'), ['resultado_final'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_situacao'), ['situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_turma_id'), ['turma_id'], unique=False)
        batch_op.create_index('ix_matriculas_turma_situacao', ['turma_id', 'situacao'], unique=False)

    op.create_table('turmas_disciplinas',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], name=op.f('fk_turmas_disciplinas_disciplina_id_disciplinas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], name=op.f('fk_turmas_disciplinas_professor_id_professores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_turmas_disciplinas_turma_id_turmas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turmas_disciplinas')),
    sa.UniqueConstraint('turma_id', 'disciplina_id', name='disciplina_unica_por_turma')
    )
    with op.batch_alter_table('turmas_disciplinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_disciplinas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_disciplinas_disciplina_id'), ['disciplina_id'], unique=False)
        batch_op.create_index('ix_turmas_disciplinas_professor', ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_disciplinas_professor_id'), ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_disciplinas_turma_id'), ['turma_id'], unique=False)

    op.create_table('aulas',
    sa.Column('turma_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.Date(), nullable=False),
    sa.Column('ordem_no_dia', sa.Integer(), nullable=False),
    sa.Column('quantidade_aulas', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('tarefa_casa', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('chamada_realizada', sa.Boolean(), nullable=False),
    sa.Column('registrada_por_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['usuarios.id'], name=op.f('fk_aulas_registrada_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_disciplina_id'], ['turmas_disciplinas.id'], name=op.f('fk_aulas_turma_disciplina_id_turmas_disciplinas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aulas')),
    sa.UniqueConstraint('turma_disciplina_id', 'data_aula', 'ordem_no_dia', name='aula_unica')
    )
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aulas_chamada_realizada'), ['chamada_realizada'], unique=False)
        batch_op.create_index(batch_op.f('ix_aulas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_aulas_data', ['data_aula'], unique=False)
        batch_op.create_index(batch_op.f('ix_aulas_data_aula'), ['data_aula'], unique=False)
        batch_op.create_index(batch_op.f('ix_aulas_turma_disciplina_id'), ['turma_disciplina_id'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('turma_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('prova', 'trabalho', 'seminario', 'participacao', 'projeto', 'recuperacao', 'outro', name='tipo_avaliacao', native_enum=False), nullable=False),
    sa.Column('peso', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('valor_maximo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_aplicacao', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('criada_por_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('peso > 0', name=op.f('ck_avaliacoes_peso_positivo')),
    sa.CheckConstraint('valor_maximo > 0', name=op.f('ck_avaliacoes_valor_maximo_positivo')),
    sa.ForeignKeyConstraint(['criada_por_id'], ['usuarios.id'], name=op.f('fk_avaliacoes_criada_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_letivos.id'], name=op.f('fk_avaliacoes_periodo_id_periodos_letivos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turma_disciplina_id'], ['turmas_disciplinas.id'], name=op.f('fk_avaliacoes_turma_disciplina_id_turmas_disciplinas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacoes'))
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_data_aplicacao'), ['data_aplicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_periodo_id'), ['periodo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_publicada'), ['publicada'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_turma_disciplina_id'), ['turma_disciplina_id'], unique=False)
        batch_op.create_index('ix_avaliacoes_vinculo_periodo', ['turma_disciplina_id', 'periodo_id'], unique=False)

    op.create_table('avisos_leituras',
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lido_em', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['aviso_id'], ['avisos.id'], name=op.f('fk_avisos_leituras_aviso_id_avisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_avisos_leituras_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avisos_leituras')),
    sa.UniqueConstraint('aviso_id', 'usuario_id', name='leitura_unica')
    )
    with op.batch_alter_table('avisos_leituras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avisos_leituras_aviso_id'), ['aviso_id'], unique=False)
        batch_op.create_index('ix_avisos_leituras_usuario', ['usuario_id', 'lido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_avisos_leituras_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('horarios',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('turma_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('tempo_aula_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.Enum('1', '2', '3', '4', '5', '6', name='dia_semana', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], name=op.f('fk_horarios_sala_id_salas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tempo_aula_id'], ['tempos_aula.id'], name=op.f('fk_horarios_tempo_aula_id_tempos_aula'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turma_disciplina_id'], ['turmas_disciplinas.id'], name=op.f('fk_horarios_turma_disciplina_id_turmas_disciplinas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_horarios_turma_id_turmas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horarios')),
    sa.UniqueConstraint('turma_id', 'dia_semana', 'tempo_aula_id', name='horario_unico_turma')
    )
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_dia_semana'), ['dia_semana'], unique=False)
        batch_op.create_index('ix_horarios_dia_tempo', ['dia_semana', 'tempo_aula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_sala_id'), ['sala_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_tempo_aula_id'), ['tempo_aula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_turma_disciplina_id'), ['turma_disciplina_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_turma_id'), ['turma_id'], unique=False)

    op.create_table('resultados_disciplinas',
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('turma_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('media_periodo_1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('media_periodo_2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('media_periodo_3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('media_periodo_4', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('media_anual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nota_recuperacao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('media_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_aulas', sa.Integer(), nullable=False),
    sa.Column('total_faltas', sa.Integer(), nullable=False),
    sa.Column('percentual_frequencia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resultado', sa.Enum('aprovado', 'aprovado_conselho', 'recuperacao', 'reprovado', 'reprovado_falta', 'cursando', name='resultado_final', native_enum=False), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name=op.f('fk_resultados_disciplinas_matricula_id_matriculas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_disciplina_id'], ['turmas_disciplinas.id'], name=op.f('fk_resultados_disciplinas_turma_disciplina_id_turmas_disciplinas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resultados_disciplinas')),
    sa.UniqueConstraint('matricula_id', 'turma_disciplina_id', name='resultado_unico')
    )
    with op.batch_alter_table('resultados_disciplinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultados_disciplinas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_disciplinas_matricula_id'), ['matricula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_disciplinas_resultado'), ['resultado'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_disciplinas_turma_disciplina_id'), ['turma_disciplina_id'], unique=False)
        batch_op.create_index('ix_resultados_situacao', ['resultado'], unique=False)

    op.create_table('frequencias',
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Enum('presente', 'falta', 'falta_justificada', 'atraso', name='situacao_presenca', native_enum=False), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('registrada_por_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], name=op.f('fk_frequencias_aula_id_aulas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name=op.f('fk_frequencias_matricula_id_matriculas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['usuarios.id'], name=op.f('fk_frequencias_registrada_por_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frequencias')),
    sa.UniqueConstraint('aula_id', 'matricula_id', name='frequencia_unica')
    )
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frequencias_aula_id'), ['aula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frequencias_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_frequencias_matricula_id'), ['matricula_id'], unique=False)
        batch_op.create_index('ix_frequencias_matricula_situacao', ['matricula_id', 'situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_frequencias_situacao'), ['situacao'], unique=False)

    op.create_table('notas',
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ausente', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('lancada_por_id', sa.Integer(), nullable=True),
    sa.Column('alterada_por_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('valor IS NULL OR valor >= 0', name=op.f('ck_notas_nota_nao_negativa')),
    sa.ForeignKeyConstraint(['alterada_por_id'], ['usuarios.id'], name=op.f('fk_notas_alterada_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], name=op.f('fk_notas_avaliacao_id_avaliacoes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancada_por_id'], ['usuarios.id'], name=op.f('fk_notas_lancada_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name=op.f('fk_notas_matricula_id_matriculas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas')),
    sa.UniqueConstraint('avaliacao_id', 'matricula_id', name='nota_unica')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_avaliacao_id'), ['avaliacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_notas_matricula', ['matricula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_matricula_id'), ['matricula_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_matricula_id'))
        batch_op.drop_index('ix_notas_matricula')
        batch_op.drop_index(batch_op.f('ix_notas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_notas_avaliacao_id'))

    op.drop_table('notas')
    with op.batch_alter_table('frequencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frequencias_situacao'))
        batch_op.drop_index('ix_frequencias_matricula_situacao')
        batch_op.drop_index(batch_op.f('ix_frequencias_matricula_id'))
        batch_op.drop_index(batch_op.f('ix_frequencias_criado_em'))
        batch_op.drop_index(batch_op.f('ix_frequencias_aula_id'))

    op.drop_table('frequencias')
    with op.batch_alter_table('resultados_disciplinas', schema=None) as batch_op:
        batch_op.drop_index('ix_resultados_situacao')
        batch_op.drop_index(batch_op.f('ix_resultados_disciplinas_turma_disciplina_id'))
        batch_op.drop_index(batch_op.f('ix_resultados_disciplinas_resultado'))
        batch_op.drop_index(batch_op.f('ix_resultados_disciplinas_matricula_id'))
        batch_op.drop_index(batch_op.f('ix_resultados_disciplinas_criado_em'))

    op.drop_table('resultados_disciplinas')
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_turma_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_turma_disciplina_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_tempo_aula_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_sala_id'))
        batch_op.drop_index('ix_horarios_dia_tempo')
        batch_op.drop_index(batch_op.f('ix_horarios_dia_semana'))
        batch_op.drop_index(batch_op.f('ix_horarios_criado_em'))

    op.drop_table('horarios')
    with op.batch_alter_table('avisos_leituras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avisos_leituras_usuario_id'))
        batch_op.drop_index('ix_avisos_leituras_usuario')
        batch_op.drop_index(batch_op.f('ix_avisos_leituras_aviso_id'))

    op.drop_table('avisos_leituras')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index('ix_avaliacoes_vinculo_periodo')
        batch_op.drop_index(batch_op.f('ix_avaliacoes_turma_disciplina_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_tipo'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_publicada'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_periodo_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_data_aplicacao'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_criado_em'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aulas_turma_disciplina_id'))
        batch_op.drop_index(batch_op.f('ix_aulas_data_aula'))
        batch_op.drop_index('ix_aulas_data')
        batch_op.drop_index(batch_op.f('ix_aulas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_aulas_chamada_realizada'))

    op.drop_table('aulas')
    with op.batch_alter_table('turmas_disciplinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_disciplinas_turma_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_disciplinas_professor_id'))
        batch_op.drop_index('ix_turmas_disciplinas_professor')
        batch_op.drop_index(batch_op.f('ix_turmas_disciplinas_disciplina_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_disciplinas_criado_em'))

    op.drop_table('turmas_disciplinas')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index('ix_matriculas_turma_situacao')
        batch_op.drop_index(batch_op.f('ix_matriculas_turma_id'))
        batch_op.drop_index(batch_op.f('ix_matriculas_situacao'))
        batch_op.drop_index(batch_op.f('ix_matriculas_resultado_final'))
        batch_op.drop_index(batch_op.f('ix_matriculas_numero'))
        batch_op.drop_index(batch_op.f('ix_matriculas_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_matriculas_criado_em'))
        batch_op.drop_index('ix_matriculas_ano_situacao')
        batch_op.drop_index(batch_op.f('ix_matriculas_ano_letivo_id'))
        batch_op.drop_index(batch_op.f('ix_matriculas_aluno_id'))

    op.drop_table('matriculas')
    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.drop_index('ix_avisos_vigencia')
        batch_op.drop_index(batch_op.f('ix_avisos_turma_id'))
        batch_op.drop_index('ix_avisos_publico_publicado')
        batch_op.drop_index(batch_op.f('ix_avisos_publico'))
        batch_op.drop_index(batch_op.f('ix_avisos_publicado'))
        batch_op.drop_index(batch_op.f('ix_avisos_prioridade'))
        batch_op.drop_index(batch_op.f('ix_avisos_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_avisos_data_inicio'))
        batch_op.drop_index(batch_op.f('ix_avisos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_avisos_autor_id'))

    op.drop_table('avisos')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_turno'))
        batch_op.drop_index(batch_op.f('ix_turmas_serie_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_sala_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_professor_regente_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_turmas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_turmas_ativa'))
        batch_op.drop_index('ix_turmas_ano_turno')
        batch_op.drop_index(batch_op.f('ix_turmas_ano_letivo_id'))

    op.drop_table('turmas')
    with op.batch_alter_table('alunos_responsaveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_responsaveis_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_alunos_responsaveis_criado_em'))
        batch_op.drop_index(batch_op.f('ix_alunos_responsaveis_aluno_id'))

    op.drop_table('alunos_responsaveis')
    with op.batch_alter_table('responsaveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsaveis_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_situacao'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_email'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_criado_em'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_cpf'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_celular'))

    op.drop_table('responsaveis')
    with op.batch_alter_table('registros_backup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_backup_criado_em'))

    op.drop_table('registros_backup')
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_professores_situacao'))
        batch_op.drop_index(batch_op.f('ix_professores_registro_funcional'))
        batch_op.drop_index(batch_op.f('ix_professores_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_professores_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_professores_email'))
        batch_op.drop_index(batch_op.f('ix_professores_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_professores_criado_em'))
        batch_op.drop_index(batch_op.f('ix_professores_cpf'))
        batch_op.drop_index(batch_op.f('ix_professores_celular'))

    op.drop_table('professores')
    with op.batch_alter_table('periodos_letivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodos_letivos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_periodos_letivos_ano_letivo_id'))

    op.drop_table('periodos_letivos')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_usuario_data')
        batch_op.drop_index('ix_logs_entidade')
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_entidade'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_acao'))
        batch_op.drop_index('ix_logs_acao_data')

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_situacao'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_setor'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_matricula_funcional'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_email'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_criado_em'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_cpf'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_celular'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_cargo'))

    op.drop_table('funcionarios')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_usuario_id'))
        batch_op.drop_index('ix_alunos_situacao_nome')
        batch_op.drop_index(batch_op.f('ix_alunos_situacao'))
        batch_op.drop_index(batch_op.f('ix_alunos_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_alunos_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_alunos_email'))
        batch_op.drop_index(batch_op.f('ix_alunos_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_alunos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_alunos_cpf'))
        batch_op.drop_index(batch_op.f('ix_alunos_codigo'))
        batch_op.drop_index(batch_op.f('ix_alunos_celular'))

    op.drop_table('alunos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('ix_usuarios_papel_ativo')
        batch_op.drop_index(batch_op.f('ix_usuarios_papel'))
        batch_op.drop_index('ix_usuarios_nome_normalizado')
        batch_op.drop_index(batch_op.f('ix_usuarios_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_criado_em'))
        batch_op.drop_index(batch_op.f('ix_usuarios_cpf'))
        batch_op.drop_index(batch_op.f('ix_usuarios_ativo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('tempos_aula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tempos_aula_turno'))
        batch_op.drop_index(batch_op.f('ix_tempos_aula_criado_em'))

    op.drop_table('tempos_aula')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_ordem'))
        batch_op.drop_index(batch_op.f('ix_series_nivel_ensino'))
        batch_op.drop_index(batch_op.f('ix_series_criado_em'))

    op.drop_table('series')
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salas_nome'))
        batch_op.drop_index(batch_op.f('ix_salas_criado_em'))

    op.drop_table('salas')
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_index('ix_disciplinas_nome_normalizado')
        batch_op.drop_index(batch_op.f('ix_disciplinas_nome'))
        batch_op.drop_index(batch_op.f('ix_disciplinas_excluido_em'))
        batch_op.drop_index(batch_op.f('ix_disciplinas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_disciplinas_codigo'))
        batch_op.drop_index(batch_op.f('ix_disciplinas_ativa'))

    op.drop_table('disciplinas')
    with op.batch_alter_table('configuracoes_escola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_escola_criado_em'))

    op.drop_table('configuracoes_escola')
    with op.batch_alter_table('anos_letivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anos_letivos_situacao'))
        batch_op.drop_index(batch_op.f('ix_anos_letivos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_anos_letivos_corrente'))
        batch_op.drop_index(batch_op.f('ix_anos_letivos_ano'))

    op.drop_table('anos_letivos')
    # ### end Alembic commands ###
